### ISSUE TITLE
Styling after the discard macro is ignored, even if it is not in the discarded area

### ISSUE THREAD

**Issue by aknorsh** [greglook/cljstyle#55]
### Target
```clojure
(defn fuga
  [x]
  (+ 1 2)
)

(let [p 1]
  #_(+ 1 2))


(defn hoge
  [x]
  (+ 1 2)
)
```

### Expected Result
```clojure
(defn fuga
  [x]
  (+ 1 2))

(let [p 1]
  #_(+ 1 2))


(defn hoge
  [x]
  (+ 1 2))
```

### Actual Result
Styling is ignored after `#_` .
```clojure
(defn fuga
  [x]
  (+ 1 2))

(let [p 1]
  #_(+ 1 2))


(defn hoge
  [x]
  (+ 1 2)
)
```

**Comment by saitouena** [comment]
This happens when a discarded form is a sub-expression of some form. I mean:

```clojure
;; I just removed a surrounding let-form `(let [p 1] ...)` from aknorsh's example
#_(+ 1 2)

(defn hoge
  [x]
  (+ 1 2)
  )  ;; this ")" will be moved to the upper line by cljstyle
```
In this case, cljstyle works well. It seems to be weird.

**Comment by greglook** [comment]
Curious - I'll add some tests and see if I can figure out what's going on.

**Comment by greglook** [comment]
Huh, this was due to some incorrect handling logic in the `edit-walk` function. If the discarded form was the last one in the subform, then `(z/right* zloc)` returns nil, and the walk concludes there are no more items to visit. Instead, it should pop back up until it finds something to go right from, or hits the root again.
